### ISSUE TITLE
Typo in resources.cpp means code won't link

### ISSUE THREAD

**Issue by guysherman** [Azure/azure-storage-cpp#71] opened 2016-06-12 21:29 UTC
in resources.cpp it defines _RECOURSES when it should define _RESOURCES.

I'm about to submit a PR that happens to fix this in an effort to get it building on OSX.

**Comment by hanzhumsft** [comment] 2016-07-01 03:37
Thanks @guysherman 
The issue is fixed by your PR #74, so we'll close this issue.

**Closed** 2016-07-01 03:37 UTC
