### ISSUE TITLE
Accessing queue with SAS token - Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by IntelligentBinary** [Azure/azure-storage-cpp#157] opened 2018-03-04 07:15 UTC
Hello,

I am using an Azure Function to generate SAS token for the storage queue. I ensure that the SAS token does not start with "?". When I use the exact same SAS token with .NET SDK, it works fine, and I am able to add the message to the queue.

However, when I use the SAS token using C++ SDK, it fails with the error below:
m_extended_error = {m_code=L"AuthenticationFailed" m_message=L"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

This is how I get the queue reference.
`auto queueClient = cloud_queue_client(storage_uri(web::uri(connectionUri)), storage_credentials(token));
this->queue = queueClient.get_queue_reference(queueName);`

And this is how I send message (JSON) to the queue:
`auto message = azure::storage::cloud_queue_message(lpcszMessage);
		this->queue.add_message(message);`

The SAS token is valid from (current time - 5 minutes) to (current time + 5 days).

**Comment by katmsft** [comment] 2018-03-07 07:27
Hi, thanks for reporting the issue. The issue is acknowledged and will be further investigated on. Please stay tuned.

**Comment by katmsft** [comment] 2018-03-19 04:48
Hi, can you provide an expired SAS token that you know worked on .NET SDK but not CPP SDK?

**Comment by katmsft** [comment] 2018-10-23 01:52
An expired SAS token will be helpful for us to understand the API version this SAS token targets to and see if there is any potential issue that may cause this SDK not being able to parse the SAS token and authenticate correctly.
Since this issue is not responded for a very long time, we will close it for now, feel free to re-open it or create another issue if this issue persist.

**Closed** 2018-10-23 02:00 UTC
Labels: question
